"""Utility helpers for the job verifier application."""

from .constants import (
    CATEGORY_WEIGHTS,
    CRITICAL_FINANCIAL_FLAGS,
    EMPLOYEE_QUERY_TEMPLATE,
    EXTREME_SCAM_PHRASES,
    FINANCIAL_RED_FLAGS,
    GENERIC_EMAIL_DOMAINS,
    JOB_BOARD_DOMAINS,
    PAYWALL_INDICATORS,
    PRESS_QUERY_TEMPLATE,
    SENSITIVE_INFO_FLAGS,
    SUSPICIOUS_TLDS,
    TOKEN_LIMIT,
    TRUSTED_BRAND_KEYWORDS,
    TRUSTED_DOMAINS,
    TRUSTED_ENTERPRISE_SUFFIXES,
    USER_AGENT,
)
from .logger import configure_logging, get_logger
from .prompts import CONTENT_ANALYSIS_SYSTEM_PROMPT, RISK_SYNTHESIS_SYSTEM_PROMPT

__all__ = [
    "CATEGORY_WEIGHTS",
    "CONTENT_ANALYSIS_SYSTEM_PROMPT",
    "CRITICAL_FINANCIAL_FLAGS",
    "EMPLOYEE_QUERY_TEMPLATE",
    "EXTREME_SCAM_PHRASES",
    "FINANCIAL_RED_FLAGS",
    "GENERIC_EMAIL_DOMAINS",
    "JOB_BOARD_DOMAINS",
    "PAYWALL_INDICATORS",
    "PRESS_QUERY_TEMPLATE",
    "RISK_SYNTHESIS_SYSTEM_PROMPT",
    "SENSITIVE_INFO_FLAGS",
    "SUSPICIOUS_TLDS",
    "TOKEN_LIMIT",
    "TRUSTED_BRAND_KEYWORDS",
    "TRUSTED_DOMAINS",
    "TRUSTED_ENTERPRISE_SUFFIXES",
    "USER_AGENT",
    "configure_logging",
    "get_logger",
]
